name: CI

on: [pull_request, push]

env:
  pnpm: 9.10.0
  RAINBOW_PROVIDER_API_KEY: RAINBOW_PROVIDER_API_KEY
  WALLETCONNECT_PROJECT_ID: YOUR_PROJECT_ID
  ALCHEMY_ID: YOUR_ALCHEMY_ID

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Cache .pnpm-store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node }}-${env.pnpm}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: npm i -g pnpm@${{env.pnpm}}
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm build
      - name: Lint and format
        run: pnpm lint
      - name: Run tests
        run: pnpm test && pnpm test:cli
